### ISSUE TITLE
合成配方冲突

### ISSUE THREAD

**Issue by ZhangMouQWQ** [GoldChick/ExtraBotany#11]
如图:
![image](https://user-images.githubusercontent.com/106049042/191899752-4c3b1234-67e1-40f6-9ea2-3135995b3628.png)
![image](https://user-images.githubusercontent.com/106049042/191899761-334f1503-1e36-4038-b5b7-c9de0ad4703c.png)

**Comment by GoldChick** [comment]
神烦花复制过去忘了改了😓

**Comment by GoldChick** [comment]
将在下个版本中修复
