### ISSUE TITLE
0.1.6.1版本启动游戏崩溃

### ISSUE THREAD

**Issue by Dr-WeiAL** [GoldChick/ExtraBotany#12]
[crash-2022-09-25_06.54.16-client.txt](https://github.com/GoldChick/ExtraBotany/files/9639710/crash-2022-09-25_06.54.16-client.txt)

**Comment by RsXLJT** [comment]
同遇到这个问题 ，0.16.1Alpha和Beta启动都崩溃
[minecraft-exported-crash-info-2022-09-25T08-08-44.zip](https://github.com/GoldChick/ExtraBotany/files/9639783/minecraft-exported-crash-info-2022-09-25T08-08-44.zip)

**Comment by GoldChick** [comment]
> [crash-2022-09-25_06.54.16-client.txt](https://github.com/GoldChick/ExtraBotany/files/9639710/crash-2022-09-25_06.54.16-client.txt)

这个崩溃的发生是因为botania本体更新之后内部文件发生了改变（我还在用432版本开发，你已经在用435了），将在下个版本中修复。
如果想要应急使用，可以使用版本低一点的额外植物学，或者432版本的植物魔法

**Comment by GoldChick** [comment]
> 同遇到这个问题 ，0.16.1Alpha和Beta启动都崩溃 [minecraft-exported-crash-info-2022-09-25T08-08-44.zip](https://github.com/GoldChick/ExtraBotany/files/9639783/minecraft-exported-crash-info-2022-09-25T08-08-44.zip)

没有看得太明白具体的问题，似乎你上传错了，并不是崩溃日志呢（找到/.minecraft/crash-report中的文件）
