### ISSUE TITLE
女仆套魔力再生问题

### ISSUE THREAD

**Issue by ZhangMouQWQ** [GoldChick/ExtraBotany#2]
![image](https://user-images.githubusercontent.com/106049042/190586994-0cace8e5-fa18-4d12-b5d3-f95dd2e1e495.png)
问题1:不会给饰品栏中的魔力戒指补充魔力。
![image](https://user-images.githubusercontent.com/106049042/190587214-0bca0a36-b2fd-4563-b0a9-f8397aede872.png)
问题2:在饰品栏有戒指的前提下无法给泰拉粉碎者提供魔力,(脱掉女仆套/或一件使其无法提供套装效果 或把戒指放在快捷栏中方可恢复正常)。
![image](https://user-images.githubusercontent.com/106049042/190587797-5e6a0788-a454-49cc-8b0f-d42b7edb84a9.png)
问题3:快捷栏中 如果戒指位置在泰拉粉碎者之后 则不会给戒指提供魔力 反之可以提供
反馈版本为 extrabotany-1.18.2-0.1.4.1.jar 测试截图时间 2022/9/16

**Comment by GoldChick** [comment]
🤯戒指和泰拉粉碎者都是植魔原本的东西，我只加了一行字，确定是额外植物学导致的吗😮问题1和问题4我记住了

**Comment by GoldChick** [comment]
问题2、3是女仆套在给泰拉粉碎者提供能量（先判断背包，再判断饰品栏）只是因为太少所以看着不明显🤔泰拉钢套则会直接跳过泰拉粉碎者

**Comment by ZhangMouQWQ** [comment]
> 问题2、3是女仆套在给泰拉粉碎者提供能量（先判断背包，再判断饰品栏）只是因为太少所以看着不明显🤔泰拉钢套则会直接跳过泰拉粉碎者

那是否应该更改女仆套也让其跳过呢?

**Comment by GoldChick** [comment]
> 那是否应该更改女仆套也让其跳过呢?

这个问题我暂时没有搞明白，明明我写的和植魔是一样的，但是表现完全不同。

**Comment by ZhangMouQWQ** [comment]
![image](https://user-images.githubusercontent.com/106049042/190881180-f7207d6f-e2d9-4e5d-8368-c3c87fd8cd15.png)
问题仍没有正确解决
问题4我认为不应该放在这个问题里 已经编辑删除
本次测试时间2022/9/18 测试版本extrabotany-1.18.2-0.1.5.1.jar

**Comment by ZhangMouQWQ** [comment]
问题2,3依旧

**Comment by GoldChick** [comment]
已经找到问题所在，将在下个版本中修复
