### ISSUE TITLE
贤者魔力指环问题

### ISSUE THREAD

**Issue by ZhangMouQWQ** [GoldChick/ExtraBotany#4]
![image](https://user-images.githubusercontent.com/106049042/190622608-6aedb5fb-fc98-4f46-8328-c4f31af08a8d.png)
无法存储魔力
(蛋糕真的成了一个谎言)

**Comment by GoldChick** [comment]
这个问题请详细描述一下，没有听懂你的意思。
是指合成的时候会损失掉魔力吗

**Comment by Dr-WeiAL** [comment]
他指的是无法给这个魔力指环补充魔力，扔到魔力池没反应

**Comment by ZhangMouQWQ** [comment]
此问题在本次更新后已解决
