### ISSUE TITLE
植物魔法词典配方显示问题

### ISSUE THREAD

**Issue by ZhangMouQWQ** [GoldChick/ExtraBotany#5]
![image](https://user-images.githubusercontent.com/106049042/190622830-8159dcfb-6e2a-4a90-bbd2-48b6e7a7a2f0.png)
![image](https://user-images.githubusercontent.com/106049042/190622856-6c89dda7-c759-44e1-8b50-4d37197f725a.png)
植物魔法词典无法正确显示配方
(虽然可以用JEI查看)

**Comment by ZhangMouQWQ** [comment]
![image](https://user-images.githubusercontent.com/106049042/190623121-effd1d9f-c8c4-41b5-b634-29b97a8e108a.png)
![image](https://user-images.githubusercontent.com/106049042/190623210-ef193aa5-d9f4-4a51-8de2-9572c90c3424.png)
还有几个没有列出

**Comment by GoldChick** [comment]
ok，将在下个版本中修复
