### ISSUE TITLE
遗物无法绑定问题(暂不确定)

### ISSUE THREAD

**Issue by ZhangMouQWQ** [GoldChick/ExtraBotany#6]
我不知道是不是我不会正确绑定遗物?

如果没有问题请自行关闭/删除此反馈

![image](https://user-images.githubusercontent.com/106049042/190623730-18ce5d70-ba65-4c68-a3b1-930573db1761.png)
![image](https://user-images.githubusercontent.com/106049042/190623787-655010e0-1b7c-46ce-b695-309a3a734e7b.png)

**Comment by GoldChick** [comment]
遗物明明放到背包里就自动绑定了的🤔尝试一下是否是其他mod所导致的

**Comment by ZhangMouQWQ** [comment]
我想,在本次更新后,这个问题解决了。
